@echo off
echo Starting Backend...
start "Backend" cmd /k "set JAVA_HOME=C:\Program Files\Java\jdk-21.0.11 ^&^& cd /d %%~dp0LokalinBackEnd\Lokalin ^&^& .\mvnw spring-boot:run"
echo Waiting for backend to start...
timeout /t 15 /nobreak
